#!/bin/bash

# build-stoww-deb: script that builds a Debian package of the stoww tool

set -e  # Exit immediately on error

# Variables
GIT_REPO="jpasquier/stoww"
BUILD_DIR=$(mktemp -d "${TMPDIR:-/tmp}/build-stoww-package.XXXXXXXX")
OUTPUT_DIR=$(pwd)

# Clean up temp directory on script exit
trap 'rm -rf "$BUILD_DIR"' EXIT

# Ensure necessary tools are installed
for cmd in git fakeroot dpkg-deb; do
    command -v "$cmd" >/dev/null 2>&1 || \
      { echo >&2 "$cmd is required but not installed. Aborting."; exit 1; }
done

# Ensure the current directory is a git repository
if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    echo "Error: Current directory is not a git repository."
    exit 1
fi

echo "Building from local repository..."
cp -a . "$BUILD_DIR/"

cd "$BUILD_DIR"
COMMIT_COUNT=$(git rev-list --count HEAD)
COMMIT_HASH=$(git rev-parse --short HEAD)
VERSION="$COMMIT_COUNT-$COMMIT_HASH"

# Check for uncommitted changes
if [[ -n $(git status --porcelain) ]]; then
    VERSION="${VERSION}-dirty"
fi

# Define destination directories
PKG_DIR="$BUILD_DIR/pkg"
DEB_DIR="$BUILD_DIR/deb"

# Create necessary directories in the package structure
mkdir -p "$PKG_DIR/usr/bin"
mkdir -p "$PKG_DIR/usr/share/zsh/vendor-completions"
mkdir -p "$PKG_DIR/DEBIAN"
mkdir -p "$DEB_DIR"

# Copy files to the target directories
cp "$BUILD_DIR/stoww" "$PKG_DIR/usr/bin/"
cp "$BUILD_DIR/zsh_completion" "$PKG_DIR/usr/share/zsh/vendor-completions/_stoww"

# Ensure that files have the correct permissions
chmod 755 "$PKG_DIR/usr/bin/stoww"
chmod 644 "$PKG_DIR/usr/share/zsh/vendor-completions/_stoww"

# Add the control file
cat >"$PKG_DIR/DEBIAN/control" <<EOL
Package: stoww
Version: $VERSION
Section: admin
Priority: optional
Architecture: all
Depends: stow
Suggests: zsh
Maintainer: Jérôme Pasquier
Description: A Wrapper for GNU Stow
Homepage: https://github.com/$GIT_REPO
Bugs: https://github.com/$GIT_REPO/issues
EOL

# Build the package using fakeroot
echo "Building the Debian package..."
fakeroot dpkg-deb --build "$PKG_DIR" "$DEB_DIR"

# Move the generated .deb package to the initial directory
mv "$DEB_DIR"/*.deb "$OUTPUT_DIR"/

echo "Package built successfully: $(ls "$OUTPUT_DIR"/*.deb)"
